# Prepare Drupal 7 installation with "content_translation"
sandbox_d7a:
	drush dl views views_ui content_translation i18n wysiwyg -y
	drush en views views_ui content_translation i18n_node i18n_taxonomy wysiwyg -y
	drush cc all

# Prepare Drupal 7 installation with "entity_translation"
sandbox_d7b:
	drush dl views views_ui wysiwyg -y
